import type { Paper } from "./types";

export const mockPapers: Paper[] = [
  {
    id: "1",
    title: "Neural Networks for Image Classification",
    author: "Dr. Alice Morgan",
    domain: "Computer Science",
    stage: "Abstract Read",
    citations: 42,
    impact: "Medium Impact",
    date: "2025-11-10",
  },
  {
    id: "2",
    title: "Protein Folding Prediction using ML",
    author: "Dr. Ron Patel",
    domain: "Biology",
    stage: "Introduction Done",
    citations: 88,
    impact: "High Impact",
    date: "2025-12-01",
  },
  {
    id: "3",
    title: "Quantum States and Entanglement",
    author: "Prof. Claire Jensen",
    domain: "Physics",
    stage: "Methodology Done",
    citations: 31,
    impact: "Medium Impact",
    date: "2025-08-19",
  },
  {
    id: "4",
    title: "Chemical Bonding Structure Analysis",
    author: "Dr. Maya Torres",
    domain: "Chemistry",
    stage: "Results Analyzed",
    citations: 65,
    impact: "High Impact",
    date: "2026-01-15",
  },
  {
    id: "5",
    title: "Statistical Models in Financial Forecasting",
    author: "Prof. Liam Cooper",
    domain: "Mathematics",
    stage: "Fully Read",
    citations: 112,
    impact: "High Impact",
    date: "2025-10-12",
  },
  {
    id: "6",
    title: "Social Behavior Prediction with Large Data",
    author: "Dr. Evelyn Scott",
    domain: "Social Sciences",
    stage: "Notes Completed",
    citations: 54,
    impact: "Medium Impact",
    date: "2025-12-20",
  },
  {
    id: "7",
    title: "Graph Algorithms and Complexity",
    author: "Dr. Isaac Turner",
    domain: "Computer Science",
    stage: "Methodology Done",
    citations: 23,
    impact: "Low Impact",
    date: "2026-02-05",
  },
  {
    id: "8",
    title: "Cellular Mutation Tracking with AI",
    author: "Dr. Zara Ali",
    domain: "Biology",
    stage: "Fully Read",
    citations: 141,
    impact: "High Impact",
    date: "2025-07-18",
  },
  {
    id: "9",
    title: "Particle Motion at High-Energy Levels",
    author: "Dr. Aaron Blake",
    domain: "Physics",
    stage: "Abstract Read",
    citations: 9,
    impact: "Unknown",
    date: "2026-02-25",
  },
  {
    id: "10",
    title: "Organic Compound Thermal Breakdown",
    author: "Prof. Julia Chen",
    domain: "Chemistry",
    stage: "Introduction Done",
    citations: 48,
    impact: "Medium Impact",
    date: "2025-09-22",
  },
  {
    id: "11",
    title: "Topology-Based Cryptography Systems",
    author: "Dr. Kevin Brooks",
    domain: "Mathematics",
    stage: "Results Analyzed",
    citations: 74,
    impact: "High Impact",
    date: "2025-08-30",
  },
  {
    id: "12",
    title: "Cultural Shifts in Digital Societies",
    author: "Dr. Nina Ruiz",
    domain: "Social Sciences",
    stage: "Abstract Read",
    citations: 12,
    impact: "Low Impact",
    date: "2026-01-11",
  },
  {
    id: "13",
    title: "GPU Optimization with Parallel Computing",
    author: "Dr. Samir Khan",
    domain: "Computer Science",
    stage: "Results Analyzed",
    citations: 87,
    impact: "Medium Impact",
    date: "2025-12-29",
  },
  {
    id: "14",
    title: "Genetic Mutation Rate Estimation",
    author: "Prof. Olivia Gray",
    domain: "Biology",
    stage: "Notes Completed",
    citations: 151,
    impact: "High Impact",
    date: "2025-06-09",
  },
  {
    id: "15",
    title: "Accelerator Physics Simulation",
    author: "Dr. Tom Rivera",
    domain: "Physics",
    stage: "Fully Read",
    citations: 199,
    impact: "High Impact",
    date: "2025-05-14",
  },
  {
    id: "16",
    title: "Chemical Reaction Kinetics",
    author: "Dr. Leah Mitchell",
    domain: "Chemistry",
    stage: "Methodology Done",
    citations: 21,
    impact: "Unknown",
    date: "2025-11-04",
  },
  {
    id: "17",
    title: "Nonlinear Equations in Climate Modeling",
    author: "Prof. Henry Schultz",
    domain: "Mathematics",
    stage: "Introduction Done",
    citations: 33,
    impact: "Medium Impact",
    date: "2026-02-07",
  },
  {
    id: "18",
    title: "Behavioral Economics and Decision Making",
    author: "Dr. Aria Lopez",
    domain: "Social Sciences",
    stage: "Results Analyzed",
    citations: 62,
    impact: "Medium Impact",
    date: "2025-08-02",
  },
  {
    id: "19",
    title: "Distributed Systems for Large-Scale Computing",
    author: "Dr. Markus Stein",
    domain: "Computer Science",
    stage: "Notes Completed",
    citations: 134,
    impact: "High Impact",
    date: "2025-03-15",
  },
  {
    id: "20",
    title: "Evolutionary Gene Mapping",
    author: "Dr. Hana O'Neil",
    domain: "Biology",
    stage: "Abstract Read",
    citations: 7,
    impact: "Low Impact",
    date: "2026-01-28",
  },
];